project_id = "lizcpvxixahyzggwjnnq"

[functions.ai-tutor]
verify_jwt = false

[functions.braintree-token]
verify_jwt = false

[functions.braintree-payment]
verify_jwt = false

[functions.create-tutor]
verify_jwt = false

[functions.check-upcoming-sessions]
verify_jwt = false

[functions.create-message-notification]
verify_jwt = false